### ISSUE TITLE
zypprepo - sles 10.4 add

### ISSUE THREAD

**Issue by mrochford** [mikeknox/puppet-zypprepo#1]
Adding a repo to a SLES 10.4 server fails saying: 

```
err: /Stage[main]/Repositories/Zypprepo[SLES10-SP4-Updates]: Could not evaluate: File /etc/zypp/zypper.conf does not contain a main section
```

the manifest contains the following.

```
zypprepo { "SLES10-SP4-Pool":
            baseurl => "http://*******/sles/10.4/SLES10-SP4-Pool/sles-10-x86_64",
            enabled => 1,
            autorefresh => 1,
            name => "SLES10-SP4-Pool",
            gpgcheck => 1,
            gpgkey => "http://*******/repo/keys/smt-repo-key.key",
            priority => 98,
            keeppackages => 0,
            type => "rpm-md",
    }
```

puppet version: 2.7.12

**Comment by mikeknox** [comment]
Hi,
I've trialled this on SLES 10.4 now, and I don't get the same error as you.
It does fail however. The provider manipulates the repo files directly and assumes that they are in /etc/zypp/repos.
This is not the case for for SLES 10.x, they are in /var/lib/zypp/db/sources/ and the file name is a hash.

While zypper is available for SLES 10.x, I've been using rug for 10.x and zypper for 11.x.
How useful would adding suport for 10.x  be?
